node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs-10.7.0') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '53423504-d966-4fee-9ddc-18f4e933bbc5') {
       def app = docker.build("reinaldocancino/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
